brain_two/urls.py
from django.contrib import admin
from django.urls import path, include
#we to let our project know about our URL app thta we manually created.

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include('todos.urls')),   #create a path, the include method
    path("", include('todos.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

todos/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views as views
from todos.views import TodosListView, TodosDeleteView, TodosDeleteView, TodosCreateView, TodosList

from todos.views import (
    TodosListView,
    TodosDetailView,
    TodosCreateView,
    TodosDeleteView,
    TodosUpdateView,
)
urlpatterns = [
    path("", TodosListView.as_view(), name="todos_list_list"),
    # path("todos/", include("todos.urls")),
    path("<int:pk>/", TodosDetailView.as_view(), name="todos_list_detail"),
    path("<int:pk>/delete/", TodosDeleteView.as_view(), name="todos_list_delete"),
    path("new/", TodosCreateView.as_view(), name="todos_list_create"),
    path("<int:pk>/edit/", TodosUpdateView.as_view(), name="todos_list_edit"),
    path('', views.TodosList, name="todos_list_list")
]

todos/models.py
from django.db import models


# from django.conf import settings

# Create your models here.


class TodosList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodosItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodosList", related_name="items",
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, CreateView, UpdateView

from todos.models import TodosList
from django.http import HttpResponse


def Todoslist(request):
    return HttpResponse("TodosList", {"success": True})

# ( I createed a function base view to connect the Url patterns together. To
# do that, we needto go into our views and render out a simple function
# base view.)


class TodosListView(ListView):
    model = TodosList
    template_name = 'todos/todoslist.html'


class TodosDetailView(DetailView):
    model = TodosList
    template_name = 'todos/todosdetail.html'


class TodosDeleteView(DeleteView):
    model = TodosList
    template_name = 'todos/todosdelete.html'


class TodosCreateView(CreateView):
    model = TodosList
    template_name = 'todos/todosnew.html'
    fields = ["name"]
    success_url = reverse_lazy("todos_list_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TodosUpdateView(UpdateView):
    model = TodosList
    template_name = 'todos/edit.html'

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
      {% endblock title %}
    </title>
  </head>
  <body>
    {% block content %}
    {% endblock content %}
  </body>
</html>

todos/templates/todos/todoscreate.html
{% extends 'base.html' %}

{% block title %}
    Create To Do Lists
{% endblock title %}
{% block content %}
    <main>
        <div class="control">
            <h1>Create a new list</h1>
            <form method="POST">
                {% csrf_token %}
                <input type="text" name="name"/>
                <button class="button">Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

todos/templates/todos/todosdelete.html
{% extends 'base.html' %}

{% block title %}
    Delete this Lists
{% endblock title %}
{% block content %}
    <main>
        <div class="delete-form">
            <h1>Are you sure you want to delete "{{ todos_list.name }}"?</h1>
            <form method="POST">
                {% csrf_token %}
                <button class="button">Delete</button>
            </form>
        </div>
    </main>
{% endblock content %}

todos/templates/todos/todosdetail.html
{% extends 'base.html' %}

{% block title %}
    {{ todoslist.name }}
{% endblock title %}
{% block content %}
    <main>
        <div>
            <h1>{{ todoslist.name }}</h1>
            <h2>Tasks</h2>
            <table>
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Due Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in todsolist.list.items.all %}
                        <tr>
                            <td>{{ item.task }}</td>
                            <td>{{ item.due_date }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock content %}

todos/templates/todos/todoslist.html
{% extends 'base.html' %}

{% block title %}
    To Do Lists
{% endblock title %}
{% block content %}
    <main>
        <div>
            <h1>My Lists</h1>
            <div>
                <p>
                    <a href="{% url "todos_list_create" %}">Create a New List</a>
                </p>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of Items</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for todoslist in todoslist_list %}
                            <tr>
                                <td>
                                    <a href="{% url "todos_list_detail" todoslist.id %}">{{ todoslist.name }}</a>
                                </td>
                                <td>{{ todoslist.items.all }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </main>
    {% endblock content %}

todos/templates/todos/todosupdate.html
{% extends 'base.html' %}

{% block title %}
    Edit the Lists {{ todoslist.name }}
{% endblock title %}
{% block content %}
    <main>
        <div class="update-form">
            <h1>Update List</h1>
            <form method="POST">
                {% csrf_token %}
                <input type="text" name="name">
                <button class="button">Delete</button>
            </form>
        </div>
    </main>
{% endblock content %}